namespace AdskConstructionCloudBreakdown
{
    public enum ProjectTypeEnum
    {
        Commercial,
        ConventionCenter,
        DataCenter,
        HotelMotel,
        Office,
        ParkingStructureGarage,
        PerformingArts,
        Retail,
        StadiumArena,
        ThemePark,
        Warehouse,
        Healthcare,
        AssistedLivingNursingHome,
        Hospital,
        MedicalLaboratory,
        MedicalOffice,
        OutPatientSurgeryCenter,
        Institutional,
        CourtHouse,
        Dormitory,
        EducationFacility,
        GovernmentBuilding,
        Library,
        MilitaryFacility,
        Museum,
        PrisonCorrectionalFacility,
        RecreationBuilding,
        ReligiousBuilding,
        ResearchFacilityLaboratory,
        Residential,
        MultiFamilyHousing,
        SingleFamilyHousing,
        Infrastructure,
        Airport,
        Bridge,
        CanalWaterway,
        DamsFloodControlReservoirs,
        HarborRiverDevelopment,
        Rail,
        Seaport,
        StreetsRoadsHighways,
        TransportationBuilding,
        Tunnel,
        WasteWaterSewers,
        WaterSupply,
        IndustrialEnergy,
        ManufacturingFactory,
        OilGas,
        Plant,
        PowerPlant,
        SolarFar,
        Utilities,
        WindFarm,
        SampleProjects,
        DemonstrationProject,
        TemplateProject,
        TrainingProject
    }

    // values taken from: https://forge.autodesk.com/en/docs/bim360/v1/overview/parameters/
    // ToDo: missing whitespaces in the enum entities might create problems. Consider to introduce a dictionary


}